language: node_js
dist: trusty
sudo: required
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '11'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
install:
  - yarn global add codecov typescript
  - yarn
script:
  - yarn run lint
  - yarn run test
  - codecov
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
